### PR TITLE
Add some terminology from the working group.

### PR DESCRIPTION
**Pull request by tommythorsen**
These added terms are mainly from the architecture proposal which can be
found here:

https://w3c.github.io/webpayments/proposals/architecture/#definitions

### CODE REVIEW

**Comment by adrianhopebailie** [comment]
+1 to merge

I'd look at the Payment Apps wiki page of Ian's for more definitions too

**Comment by tommythorsen** [comment]
@adrianhopebailie and @ianbjacobs 

> I'd look at the Payment Apps wiki page of Ian's for more definitions too

The latest commit in this PR adds these definitions as well. Does that look alright to you guys?

**Comment by adrianhopebailie** [comment]
LGTM

@ianbjacobs - make sure you've got this in your local copy before you start your editing!

**Comment by tommythorsen** [comment]
@adrianhopebailie or @ianbjacobs 
Hmm. Was this supposed to have gone into the `gh-pages` branch rather than the `master` branch? How is the relationship between those two branches handled in this repo? Should I make a new pull request with the same changes for `gh-pages`?

**Comment by tommythorsen** [comment]
I made a new PR here: https://github.com/w3c/webpayments-ig/pull/41, which adds these same changes to the `gh-pages` branch.

**Comment by adrianhopebailie** [comment]
I have a confession to make. I merged this thinking it was a change to the architecture proposal in the WG repo. I shouldn't really be merging content in the IG repo at all so happy for someone to roll my change back.

That said, this repo shouldn't have a `master` branch. The norm for W3C repos is to make `gh-pages` the default and drop master.

**Pull request merged**
